#
# Note:
#
# - For packages under k8s.io, upgrade client-go first then contraints its
#   dependencies manually. See https://github.com/kubernetes/client-go/blob/v4.0.0/INSTALL.md#dep.
#
[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.8"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.0.0"

# Required by https://github.com/kubernetes/apiserver/blob/release-1.8/Godeps/Godeps.json
[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"

# Required by k8s.io/api.
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.8"
