apiVersion: v1
kind: Service
metadata:
  name: remote-zookeeper
  labels:
    app: zookeeper
    name: remote-zookeeper
spec:
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper
    name: remote-zookeeper
