apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zookeeper
    name: remote-zookeeper
  name: remote-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      name: remote-zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        name: remote-zookeeper
    spec:
      containers:
      - env:
        - name: ZOO_STANDALONE_ENABLED
          value: 'true'
        image: index-dev.qiniu.io/kelibrary/zookeeper:3.4.11
        imagePullPolicy: IfNotPresent
        name: zookeeper
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: follower
          protocol: TCP
        - containerPort: 3888
          name: election
          protocol: TCP
